name: "Gets and stores the new version name so we can use it do deploy"
description: "Boilerplate steps"
runs:
  using: "composite"
  steps:

    # Setup versionName because we love it
    - name: Get next version name
      id: new-version
      uses: proudust/gh-describe@v1.5.3

    # Write versionName into build file to use properly in the future
    - name: Write version into build file
      shell: bash
      run: |
        mkdir build
        touch version-name.txt
        echo "${{ steps.new-version.outputs.describe }}" >> build/version-name.txt

    # Put everything we need into gradle.properties to build properly
    - name: Inject sign into gradle.properties
      shell: bash
      run: |
        echo "OSSRH_USERNAME=$OSSRH_USERNAME" >> gradle.properties
        echo "OSSRH_PASSWORD=$OSSRH_PASSWORD" >> gradle.properties
        echo "signing.keyId=$SIGN_KEYID" >> gradle.properties
        echo "signing.password=$SIGN_PASSWORD" >> gradle.properties
        echo "signing.secretKeyRingFile=$PWD/$SIGN_FILENAME" >> gradle.properties
        cat gradle.properties
