name: "Configure Java and Gradle"
description: "Boilerplate steps"
runs:
  using: "composite"
  steps:

    # Setup JDK 17 to build properly
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: temurin
        cache: gradle

    # Setup Gradle because without it, nothing happens
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    # Setup versionName because we love it
    - name: Get next version name
      id: new-version
      uses: proudust/gh-describe@v1.5.3

    - name: Write version into build file
      run: |
        mkdir build
        touch version-name.txt
        echo "${{ steps.new-version.outputs.describe }}" >> build/version-name.txt