version: 4
jobs:
  checkout-repo:
    working_directory: ~/arch-toolkit
    docker:
      - image: cimg/android:2022.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
           paths:
              - ~/.gradle
           key: gradle-{{ checksum "build.gradle" }}

  ktLint:
    working_directory: ~/arch-toolkit
    docker:
      - image: cimg/android:2022.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Run KtLint
          command: ./gradlew ktLint

      - store_artifacts:
          path: build/reports/ktlint
          destination: reports/ktlint

  lint:
    working_directory: ~/arch-toolkit
    docker:
      - image: cimg/android:2022.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Run Lint
          command: ./gradlew lintDebug

      - store_artifacts:
          path: build/reports/lint
          destination: reports/lint

  livedata:
    working_directory: ~/arch-toolkit
    docker:
      - image: cimg/android:2022.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Run Livedata test
          command: ./gradlew :toolkit:livedata:jacocoTestReport

      - store_artifacts:
          path: toolkit/livedata/build/reports/jacoco/
          destination: reports/livedata

      - save_cache:
           paths:
              - ~/toolkit/livedata/build/jacoco
              - ~/toolkit/livedata/build/outputs/code-coverage/connected
           key: jacoco-files-{{ checksum "toolkit/livedata/build.gradle" }}

  recycler-adapter:
    working_directory: ~/arch-toolkit
    docker:
      - image: cimg/android:2022.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Run Recycler Adapter test
          command: ./gradlew :toolkit:recycler-adapter:jacocoTestReport

      - store_artifacts:
          path: toolkit/recycler-adapter/build/reports/jacoco/
          destination: reports/recycler-adapter

      - save_cache:
           paths:
              - ~/toolkit/recycler-adapter/build/jacoco
              - ~/toolkit/recycler-adapter/build/outputs/code-coverage/connected
           key: jacoco-files-{{ checksum "toolkit/recycler-adapter/build.gradle" }}

  statemachine:
    working_directory: ~/arch-toolkit
    docker:
      - image: cimg/android:2022.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Run Statemachine test
          command: ./gradlew :toolkit:statemachine:jacocoTestReport

      - store_artifacts:
          path: toolkit/statemachine/build/reports/jacoco/
          destination: reports/statemachine

      - save_cache:
           paths:
              - ~/toolkit/statemachine/build/jacoco
              - ~/toolkit/statemachine/build/outputs/code-coverage/connected
           key: jacoco-files-{{ checksum "toolkit/statemachine/build.gradle" }}

  delegate:
    working_directory: ~/arch-toolkit
    docker:
      - image: cimg/android:2022.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Run Delegate test
          command: ./gradlew :toolkit:delegate:jacocoTestReport

      - store_artifacts:
          path: toolkit/delegate/build/reports/jacoco/
          destination: reports/delegate

      - save_cache:
           paths:
              - ~/toolkit/delegate/build/jacoco
              - ~/toolkit/delegate/build/outputs/code-coverage/connected
           key: jacoco-files-{{ checksum "toolkit/delegate/build.gradle" }}

  livedata-deploy:
    working_directory: ~/arch-toolkit
    docker:
      - image: cimg/android:2022.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Deploy Livedata
          command: ./gradlew :toolkit:livedata:bintrayUpload

  recycler-adapter-deploy:
    working_directory: ~/arch-toolkit
    docker:
      - image: cimg/android:2022.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Deploy Recycler Adapter
          command: ./gradlew :toolkit:recycler-adapter:bintrayUpload

  statemachine-deploy:
    working_directory: ~/arch-toolkit
    docker:
      - image: cimg/android:2022.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Deploy Statemachine
          command: ./gradlew :toolkit:statemachine:bintrayUpload

  delegate-deploy:
    working_directory: ~/arch-toolkit
    docker:
      - image: cimg/android:2022.04
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle" }}
      - run:
          name: Deploy Delegate
          command: ./gradlew :toolkit:delegate:bintrayUpload

workflows:
  version: 2
  lint-test-deploy:
    jobs:
      - checkout-repo
      - ktLint:
          requires:
            - checkout-repo
      - lint:
          requires:
            - checkout-repo
      - livedata:
          requires:
            - lint
            - ktLint
      - recycler-adapter:
          requires:
            - lint
            - ktLint
      - statemachine:
          requires:
            - lint
            - ktLint
      - delegate:
          requires:
            - lint
            - ktLint
      - livedata-deploy:
          requires:
            - livedata
          filters:
            branches:
              only: master
      - recycler-adapter-deploy:
          requires:
            - recycler-adapter
          filters:
            branches:
              only: master
      - statemachine-deploy:
          requires:
            - statemachine
          filters:
            branches:
              only: master
      - delegate-deploy:
          requires:
            - delegate
          filters:
            branches:
              only: master
