version: 2
jobs:
  checkout_repo:
    working_directory: ~/arch-toolkit
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "toolkit/livedata/build.gradle" }}-{{ checksum  "toolkit/recycler-adapter/build.gradle" }}-{{ checksum  "toolkit/statemachine/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "toolkit/livedata/build.gradle" }}-{{ checksum  "toolkit/recycler-adapter/build.gradle" }}-{{ checksum  "toolkit/statemachine/build.gradle" }}

  ktLint:
    steps:
      - run:
        name: Run KtLint
        command: ./gradlew ktLint

      - store_artifacts:
        path: build/reports/ktlint
        destination: reports/ktlint

#  lint:
#    working_directory: ~/arch-toolkit
#    docker:
#      - image: circleci/android:api-25-alpha
#    environment:
#      JVM_OPTS: -Xmx3200m
#    steps:
#      - checkout
#      - run:
#        name: Run Lint
#        command: ./gradlew lintDebug
#      - store_artifacts:
#          path: build/reports/xml
#          destination: reports/lint/xml
#      - store_artifacts:
#          path: build/reports/html
#          destination: reports/lint/html

workflows:
  version: 2
  teste:
    jobs:
      - checkout_repo
      - ktLint:
        requires:
          - checkout_repo
#      - lint:
#        requires:
#          - checkout
