version: 2.1

commands: # a reusable command with parameters
  lint-module:
    parameters:
      module:
        default: ""
        type: string
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run: ./gradlew <<parameters.module>>:lint

  test-module:
    parameters:
      module:
        default: ""
        type: string
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run: ./gradlew <<parameters.module>>:testDebugUnitTest

jobs:
  build:
    docker:
      - image: cimg/android:2022.04
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}

  # Delegate Jobs
  lint-delegate:
    docker:
      - image: cimg/android:2022.04
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - lint-module:
          module: ":toolkit:delegate"
  test-delegate:
    docker:
      - image: cimg/android:2022.04
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - test-module:
          module: ":toolkit:delegate"

  # LiveData Jobs
  lint-livedata:
    docker:
      - image: cimg/android:2022.04
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - lint-module:
          module: ":toolkit:livedata"
  test-livedata:
    docker:
      - image: cimg/android:2022.04
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - test-module:
          module: ":toolkit:livedata"

  # Recycler Adapter Jobs
  lint-recycler-adapter:
    docker:
      - image: cimg/android:2022.04
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - lint-module:
          module: ":toolkit:recycler-adapter"
  test-recycler-adapter:
    docker:
      - image: cimg/android:2022.04
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - test-module:
          module: ":toolkit:recycler-adapter"

  # StateMachine Jobs
  lint-statemachine:
    docker:
      - image: cimg/android:2022.04
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - lint-module:
          module: ":toolkit:statemachine"
  test-statemachine:
    docker:
      - image: cimg/android:2022.04
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - test-module:
          module: ":toolkit:statemachine"

  # Maldade Jobs
  lint:
    docker:
      - image: cimg/android:2022.04
    environment:
      JVM_OPTS: -Xmx3200m
    parameters:
      module:
        default: ""
        type: string
    steps:
      - lint-module:
         module: <<parameters.module>>

  test:
    docker:
      - image: cimg/android:2022.04
    environment:
      JVM_OPTS: -Xmx3200m
    parameters:
      module:
        default: ""
        type: string
    steps:
      - test-module:
          module: <<parameters.module>>

workflows:
  pull_request:
    jobs:
      - build

      - lint:
          matrix:
            alias: lint-all-modules
            parameters:
              module:
                - :toolkit:delegate
                - :toolkit:livedata
                - :toolkit:recycler-adapter
                - :toolkit:statemachine
          requires:
            - build
      - test:
          matrix:
            alias: test-all-modules
            parameters:
              module:
                - :toolkit:delegate
                - :toolkit:livedata
                - :toolkit:recycler-adapter
                - :toolkit:statemachine
          requires:
            - lint-all-modules

      # Delegate Flow
      - lint-delegate:
          requires:
            - build
      - test-delegate:
          requires:
            - lint-delegate

      # LiveData Flow
      - lint-livedata:
          requires:
            - build
      - test-livedata:
          requires:
            - lint-livedata

      # Recycler Adapter Flow
      - lint-recycler-adapter:
          requires:
            - build
      - test-recycler-adapter:
          requires:
            - lint-recycler-adapter

      # StateMachine Flow
      - lint-statemachine:
          requires:
            - build
      - test-statemachine:
          requires:
            - lint-statemachine