version: 2
jobs:
  checkout_repo:
    working_directory: ~/arch-toolkit
    docker:
      - image: circleci/android:api-25-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

  ktLint:
    working_directory: ~/arch-toolkit
    docker:
      - image: circleci/android:api-25-alpha
    steps:
      - checkout
      - run:
          name: Run KtLint
          command: ./gradlew ktLint

      - store_artifacts:
          path: app/build/reports
          destination: reports/ktlint

workflows:
  version: 2
  teste:
    jobs:
      - checkout_repo
      - ktLint:
          requires:
            - checkout_repo