version: 2.1

executors:
  android:
    docker:
      - image: cimg/android:2022.06

commands:
  default:
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

jobs:
  build:
    executor: android
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - default
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD -Psigning.secretKeyRingFile=$PWD/
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}

  # Maldade Jobs
  lint:
    executor: android
    environment:
      JVM_OPTS: -Xmx3200m
    parameters:
      module:
        default: ""
        type: string
    steps:
      - default
      - run: ./gradlew :<<parameters.module>>:lint -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD
      - run: ./gradlew :<<parameters.module>>:ktLint -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD

  test:
    executor: android
    environment:
      JVM_OPTS: -Xmx3200m
    parameters:
      module:
        default: ""
        type: string
    steps:
      - default
      - run: ./gradlew :<<parameters.module>>:testDebugUnitTest -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD

  # FIXME Run all module in parallel is a problem to sonatype =(
  deploy:
    executor: android
    environment:
      JVM_OPTS: -Xmx3200m
    parameters:
      module:
        default: ""
        type: string
    steps:
      - default
      - run: ./gradlew :<<parameters.module>>:assembleRelease -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD
      - run: ./gradlew :<<parameters.module>>:publishRelease -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD

  # Deploys each modules
  deploy-delegate:
    executor: android
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - default
      - run: ./gradlew :toolkit:delegate:assembleRelease -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD
      - run: ./gradlew :toolkit:delegate:publishRelease -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD

  deploy-livedata:
    executor: android
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - default
      - run: ./gradlew :toolkit:livedata:assembleRelease -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD
      - run: ./gradlew :toolkit:livedata:publishRelease -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD

  deploy-recycler-adapter:
    executor: android
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - default
      - run: ./gradlew :toolkit:recycler-adapter:assembleRelease -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD
      - run: ./gradlew :toolkit:recycler-adapter:publishRelease -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD

  deploy-statemachine:
    executor: android
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - default
      - run: ./gradlew :toolkit:statemachine:assembleRelease -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD
      - run: ./gradlew :toolkit:statemachine:publishRelease -PDEVELOPER_ID=$DEVELOPER_ID -PDEVELOPER_NAME=$DEVELOPER_NAME -PDEVELOPER_EMAIL=$DEVELOPER_EMAIL -POSSRH_USERNAME=$OSSRH_USERNAME -POSSRH_PASSWORD=$OSSRH_PASSWORD -Psigning.keyId=$SIGNING_KEYID -Psigning.password=$SIGNING_PASSWORD

workflows:
  pull_request:
    jobs:
      # Builds Project and saves build cache
      - build

      # Runs android lint and KtLint
      - lint:
          matrix:
            alias: lint-all-modules
            parameters:
              module:
                - toolkit:delegate
                - toolkit:livedata
                - toolkit:recycler-adapter
                - toolkit:statemachine
          name: Lint <<matrix.module>>
          requires:
            - build

      # Runs Unit tests
      - test:
          matrix:
            alias: unit-test-all-modules
            parameters:
              module:
                - toolkit:delegate
                - toolkit:livedata
                - toolkit:recycler-adapter
                - toolkit:statemachine
          name: Test <<matrix.module>>
          requires:
            - Lint <<matrix.module>>

      # Ask for approval to run deploy
      - hold-deploy:
          type: approval
          requires:
            - unit-test-all-modules
          filters:
            branches:
              only:
                - master

      # FIXME Run all module in parallel is a problem to sonatype =(
      #      # Deploys all modules
      #      - deploy:
      #          matrix:
      #            alias: deploy-all-modules
      #            parameters:
      #              module:
      #                - toolkit:delegate
      #                - toolkit:livedata
      #                - toolkit:recycler-adapter
      #                - toolkit:statemachine
      #          name: Deploy <<matrix.module>>
      #          requires:
      #            - hold-deploy

      # Deploys each modules
      - deploy-delegate:
          requires:
            - hold-deploy
      - deploy-livedata:
          requires:
            - deploy-delegate
      - deploy-recycler-adapter:
          requires:
            - deploy-livedata
      - deploy-statemachine:
          requires:
            - deploy-recycler-adapter
