version: 2.1

executors:
  android:
    docker:
      - image: cimg/android:2022.04

commands:
  default:
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}

  lint-module:
    description: Runs Android Lint and KtLint
    parameters:
      module:
        default: ""
        type: string
    steps:
      - default
      - run: ./gradlew <<parameters.module>>:lint
      - run: ./gradlew <<parameters.module>>:ktLint

  test-module:
    description: Runs Unit Test
    parameters:
      module:
        default: ""
        type: string
    steps:
      - default
      - run: ./gradlew <<parameters.module>>:testDebugUnitTest

jobs:
  build:
    executor: android
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - default
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}

  # Maldade Jobs
  lint:
    executor: android
    environment:
      JVM_OPTS: -Xmx3200m
    parameters:
      module:
        default: ""
        type: string
      module-name:
        default: ""
        type: string
    steps:
      - lint-module:
          module: <<parameters.module>>

  test:
    executor: android
    environment:
      JVM_OPTS: -Xmx3200m
    parameters:
      module:
        default: ""
        type: string
    module-name:
      default: ""
      type: string
    steps:
      - test-module:
          module: <<parameters.module>>

workflows:
  pull_request:
    jobs:
      # Builds Project and saves build cache
      - build

      # Runs android lint and KtLint
      - lint:
          matrix:
            alias: lint-all-modules
            parameters:
              module:
                - :toolkit:delegate
                - :toolkit:livedata
                - :toolkit:recycler-adapter
                - :toolkit:statemachine
              module-name:
                - Delegate
                - Livedata
                - Recycler Adapter
                - StateMachine
          name: Lint <<matrix.module-name>>
          requires:
            - build

      # Runs Unit tests
      - test:
          matrix:
            alias: unit-test-all-modules
            parameters:
              module:
                - :toolkit:delegate
                - :toolkit:livedata
                - :toolkit:recycler-adapter
                - :toolkit:statemachine
              module-name:
                - Delegate
                - Livedata
                - Recycler Adapter
                - StateMachine
          name: Test <<matrix.module-name>>
          requires:
            - Lint <<matrix.module-name>>