name: Generate Release Tag and Publish Artifacts

on:
  push:
    branches:
      - master

jobs:

  generate-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate next tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          chmod +x .github/scripts/tag.sh
          ./.github/scripts/tag.sh

  pre-build:
    runs-on: ubuntu-latest
    needs: generate-tag
    outputs:
      modules: ${{ steps.read-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4

      - name: Base Setup
        id: base-setup
        uses: ./.github/actions/setup-gradle

      - name: Read Modules
        id: read-modules
        run: |
          ./gradlew :toolkit:publishModules
          MODULES=$(cat $PWD/toolkit/build/modules.txt)
          echo "modules=$MODULES" >> "$GITHUB_OUTPUT"


  publish:
    runs-on: ubuntu-latest
    needs: pre-build
    strategy:
      matrix:
        module: ${{fromJSON(needs.pre-build.outputs.modules)}}
      fail-fast: true
      max-parallel: 1

    steps:
      - uses: actions/checkout@v4

      - name: Base Setup
        id: base-setup
        uses: ./.github/actions/setup-gradle

      - name: Version Name
        id: version-name
        uses: ./.github/actions/version-name
        with:
          # Sonatype Credentials
          ossrh_username: ${{ secrets.OSSRH_USERNAME }}
          ossrh_password: ${{ secrets.OSSRH_PASSWORD }}

          # Sign Credentials
          sign_keyid: ${{ secrets.SIGN_FILENAME }}
          sign_password: ${{ secrets.SIGN_KEYID }}
          sign_filename: ${{ secrets.SIGN_PASSWORD }}

      - name: Build ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:assembleRelease

      - name: Publish ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:publishToolkitPublicationToSonatypeRepository

