name: Generate Release Tag

on:
  push:
    branches:
      - master

jobs:
  generate-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate next tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          chmod +x .github/scripts/tag.sh
          ./.github/scripts/tag.sh