name: Generate Release Tag and Publish Artifacts

on:
  push:
    branches:
      - master

jobs:

  generate-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate next tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          chmod +x .github/scripts/tag.sh
          ./.github/scripts/tag.sh

  pre-build:
    runs-on: ubuntu-latest
    needs: generate-tag
    outputs:
      modules: ${{ steps.read-modules.outputs.modules }}
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Read Modules
        id: read-modules
        run: |
          ./gradlew :toolkit:publishModules
          MODULES=$(cat $PWD/toolkit/build/modules.txt)
          echo "modules=$MODULES" >> "$GITHUB_OUTPUT"


  publish:
    runs-on: ubuntu-latest
    needs: pre-build
    strategy:
      matrix:
        module: ${{fromJSON(needs.pre-build.outputs.modules)}}
      fail-fast: true
      max-parallel: 1

    env:
      # Sonatype Credentials
      OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
      # Sign Credentials
      SIGN_FILENAME: ${{ secrets.SIGN_FILENAME }}
      SIGN_KEYID: ${{ secrets.SIGN_KEYID }}
      SIGN_PASSWORD: ${{ secrets.SIGN_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Inject sign into local.properties
        run: |
          echo "signing.keyId=$SIGN_KEYID" >> gradle.properties
          echo "signing.password=$SIGN_PASSWORD" >> gradle.properties
          echo "signing.secretKeyRingFile=$PWD/$SIGN_FILENAME" >> gradle.properties
          cat gradle.properties

      - name: Build ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:assembleRelease

      - name: Publish ${{ matrix.module }}
        run: ./gradlew :${{ matrix.module }}:publishToolkitPublicationToSonatypeRepository

