name:

on:
  push

jobs:

  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Base Setup
        id: base-setup
        uses: ./.github/actions/setup-gradle

      - name: Version Name
        id: version-name
        uses: ./.github/actions/version-name

      - name: Teste Version2
        run: ./gradlew :toolkit:testeVersion
