name:

on:
  push

jobs:

  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Teste Version1
        id: bacate
        uses: proudust/gh-describe@v1.5.3

      - name: Teste Version2
        run: |
          mkdir build
          touch version-name.txt
          echo "${{ steps.bacate.outputs.describe }}" >> build/version-name.txt
          ./gradlew :toolkit:testeVersion
