name:

on:
  push

jobs:

  pre-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      -  id: base-setup
         uses: ./.github/actions/setup-gradle

      -  id: version-name
         uses: ./.github/actions/version-name

      - name: Teste Version2
        run: ./gradlew :toolkit:testeVersion
