name:

on:
  push

jobs:

  # Generates a new tag and submit it into repository <3
  generate-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate next tag
        run: echo "UHUL"

  pre-build:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.publishing-modules.outputs.modules }}
    steps:
      - name: Clone Repo
        uses: actions/checkout@v4

      - name: Base Setup
        uses: ./.github/actions/setup-gradle

      - name: List of Modules
        id: publishing-modules
        uses: ./.github/actions/publishing-modules

  publish:
    runs-on: ubuntu-latest
    needs:
      - generate-tag
      - pre-build
    strategy:
      matrix:
        module: ${{ fromJSON(needs.pre-build.outputs.modules) }}

    steps:
      - uses: actions/checkout@v4
